name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
      # this is a function in github allow as to acced metafdata and throw it in json format
        run: echo "${{ toJSON(github) }}