name: First Workflow
on: workflow_dispatch # workflow should manually runs
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Introduce
        run:  |
          echo "Hallo my nameis salima"
          echo "I am devops Engineer"
